version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    environment:
      - HOST=0.0.0.0
    ports:
      - '8080:80'
    tty: true
    volumes:
      - ./frontend/src/dist:/usr/share/nginx/html
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - '9000:3000'
    depends_on:
      - mongo
    environment:
      - APP_PORT=3000
    command: npm run start
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USERNAME: ${MONGO_DB_USER}
      MONGO_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - ./database/mongo-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ~/mongo-data/jukebox:/data/db
