version: "3"
services:
  frontend:
    build: ./frontend
    environment:
      - HOST=0.0.0.0
    command: npm run dev
    volumes:
      - ./frontend/src:/nodeapp/src
    ports:
      - '3000:3000'
  stellar-service:
    build: ./stellar-operations
    tty: true
    volumes:
      - ./stellar-operations/src:/nodeapp/src
    ports:
      - '3001:3000'
    environment:
      - TEST=3000
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - '3002:3000'
    volumes:
      - ./backend/src:/nodeapp/src
    depends_on:
      - mongo
    environment:
      - APP_URL=http://localhost:8082/
      - APP_PORT=3000
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: jukebox
      MONGO_USERNAME: admin
      MONGO_PASSWORD: 1234567
    volumes:
      - ./database/mongo-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
