export const songs = [
  {
    id: 1,
    name: 'Voljela me nije nijedna',
    author: 'Branimir Štulić',
    length: '3:58',
    src: require('@/assets/audio/Branimir Štulić _VОЉЕLА МЕ NIЈЕ NIJEDNА_.mp3').default,
  },
  {
    id: 2,
    name: 'Budi kao more',
    author: 'Indexi',
    length: '4:01',
    src: require('@/assets/audio/Indexi - Budi kao more - (Audio).mp3').default,
  },
  {
    id: 3,
    name: 'Košulja plava',
    author: 'Novi Fosili',
    length: '3:52',
    src: require('@/assets/audio/Novi Fosili _Košulja Plava _ (1981.).mp3').default,
  },
  {
    id: 4,
    name: 'Heroj ulice',
    author: 'Prljavo Kazalište',
    length: '4:42',
    src: require('@/assets/audio/PRLJAVO KAZALIŠTE- Heroj ulice.mp3').default,
  },
  {
    id: 5,
    name: 'Surprise song',
    author: '?',
    length: '3:32',
    src: require('@/assets/audio/Surprise song.mp3').default,
  },
  {
    id: 6,
    name: 'Yesterday',
    author: 'The Beatles',
    length: '2:06',
    src: require('@/assets/audio/The Beatles - Yesterday.mp3').default,
  },
  {
    id: 7,
    name: 'Wish You Were Here',
    author: 'Pink Floyd',
    length: '4:54',
    src: require('@/assets/audio/Pink Floyd - Wish You Were Here.mp3').default,
  },
  {
    id: 8,
    name: 'Knockin\' On Heaven\'s Door',
    author: 'Guns N\' Roses',
    length: '4:54',
    src: require('@/assets/audio/Guns N\' Roses   Knockin\' On Heaven\'s Door.mp3').default,
  },
  {
    id: 9,
    name: 'Can\'t Stop',
    author: 'Red Hot Chili Peppers',
    length: '4:39',
    src: require('@/assets/audio/Red Hot Chili Peppers - Can\'t Stop.mp3').default,
  },
  {
    id: 10,
    name: 'Wonderwall',
    author: 'Oasis',
    length: '4:39',
    src: require('@/assets/audio/Oasis - Wonderwall.mp3').default,
  },
];
